--conversion deadlock
--transaction 2

SET DEADLOCK_PRIORITY LOW

DECLARE @RETRY_COUNT_CURRENT INT
DECLARE @RETRY_COUNT_MAXIMUM INT
DECLARE @ERROR_NUM INT
DECLARE @ERROR_MSG NVARCHAR(MAX)
 
SET @ERROR_NUM = 0
SET @RETRY_COUNT_CURRENT = 0
SET @RETRY_COUNT_MAXIMUM = 3
 

WHILE @RETRY_COUNT_CURRENT <  @RETRY_COUNT_MAXIMUM
BEGIN
    BEGIN TRANSACTION
    BEGIN TRY
			exec ttnha_view 'BT0006'
			exec ttnha__update  'BT0006',6,N'Còn trống',N'Đường số 1',N'Quận 8***',N'Trung tâm',N'TP HCM',36000000.0,NULL,NULL,'BT',5,'CN0002',8,'2020-10-21','2020-11-21'
			
       COMMIT
                   
       BREAK
   END TRY
   BEGIN CATCH
     SELECT @ERROR_NUM = ERROR_NUMBER(), @ERROR_MSG = ERROR_MESSAGE()
     PRINT @ERROR_MSG
     PRINT @ERROR_NUM
     ROLLBACK
     SET @RETRY_COUNT_CURRENT = @RETRY_COUNT_CURRENT + 1
     WAITFOR DELAY '00:00:05'
     CONTINUE
   END CATCH;
END

